# Generated by Django 2.1.3 on 2018-11-17 14:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mt_core', '0002_auto_20181117_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=191)),
                ('db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mt_core.DbDetails')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userdb',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userdb',
            name='db',
        ),
        migrations.RemoveField(
            model_name='userdb',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserDb',
        ),
        migrations.AlterUniqueTogether(
            name='domaindb',
            unique_together={('name', 'db')},
        ),
    ]
