version: '3'
services:
    db:
        image: mysql:5.7.22
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: djangothon
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        networks:
            - back-tier
    db2:
        image: mysql:5.7.22
        ports:
            - "3308:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: user1.app.com
            MYSQL_USER: user
            MYSQL_PASSWORD: user
        networks:
            - back-tier
    db3:
        image: mysql:5.7.22
        ports:
            - "3309:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: user2.app.com
            MYSQL_USER: user
            MYSQL_PASSWORD: user
        networks:
            - back-tier
    redis:
        image: redis:4.0.9
        command: ["redis-server", "--appendonly", "yes"]
        ports:
            - "6381:6379"
        networks:
            - back-tier
networks:
  back-tier: