version: '3'
services:
    db:
        image: mysql:5.7.22
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: djangothon
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        networks:
            - back-tier
    db2:
        image: mysql:5.7.22
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: djangothon
            MYSQL_USER: user
            MYSQL_PASSWORD: user
        networks:
            - back-tier
networks:
  back-tier: